simplemoc/polls/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('contato/', views.contato, name='contato')
]

simplemoc/simplemoc/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('entrar/', LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
    path('sair/', LogoutView.as_view(next_page = 'polls:home'), name='logout'),
    path('cadastro/', views.register, name='register'),
    path('editar/', views.edit, name='edit'),
    path('editar-senha/', views.edit_password, name='edit_password'),
    path('resetar-senha/', views.password_reset, name='password_reset'),
    path('confirmar-nova-senha/<key>/', views.password_reset_confirm, name='password_reset_confirm'),
] 

simplemoc/simplemoc/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.index, name='index'),
    path('<slug>/', views.details, name='details'),
    path('<slug>/incricao/', views.enrollment, name='enrollment'),
    path('<slug>/cancelar-inscricao/', views.undo_enrollment, name='undo_enrollment'),
    path('<slug>/anuncios/', views.announcements, name='announcements'),
]

simplemoc/simplemoc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('polls.urls', 'polls'), namespace='polls')),
    path('conta/', include(('simplemoc.accounts.urls'), namespace='accounts')),
    path('admin/', admin.site.urls),
    path('cursos/', include(('simplemoc.courses.urls', 'courses'), namespace='courses')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemoc/simplemoc/accounts/models.py
import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import (
    AbstractBaseUser, PermissionsMixin, UserManager)
from django.conf import settings


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Nome de Usuário',
        max_length=30,
        unique=True,
        validators=[validators.RegexValidator(re.compile('^[\\w.@+-]+$'),
            'O nome de usuário só pode conter letras, digitos ou os seguintes '
            'caracteres: @/./+/-/_', 'invalid')]
    )
    email = models.EmailField('E-mail', unique=True)
    name = models.CharField('Nome', max_length=100, blank=True)
    is_active = models.BooleanField('Está ativo?', blank=True, default=True)
    is_staff = models.BooleanField(
        'É administrador?', blank=True, default=False)
    date_joined = models.DateTimeField('Data de entrada', auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'


class PasswordReset(models.Model):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT, verbose_name='Usuário',
        # related_name='resets'
    )
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    confirmed = models.BooleanField('Confirmado?', default=False, blank=True)

    def __str__(self):
        return '{0} em {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Nova Senha'
        verbose_name_plural = 'Novas Senhas'
        ordering = ['-created_at']

simplemoc/simplemoc/courses/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings


class CourseManager(models.Manager):

    def search(self, query):
        return self.get_queryset().filter(
            models.Q(name__icontains=query) | \
            models.Q(description__icontains=query)
        )


class Course(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Atalho')
    description = models.TextField('Descrição', blank=True)
    about = models.TextField('Sobre o curso', blank=True)
    start_date = models.DateField('Data de início', null=True, blank=True)
    image = models.ImageField(
        upload_to='courses/images', verbose_name='Imagem',
        null=True, blank=True
    )

    created_at = models.DateTimeField('Criado em ', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em ', auto_now=True)

    objects = CourseManager()

    def __str__(self):
        return self.name 

    def get_absolute_url(self):
        return reverse('courses:details', args=(self.slug,))
    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        ordering = ['name']


class Enrollment(models.Model):

    STATUS_CHOICES = (
        (0, 'Pendente'),
        (1, 'Aprovedo'),
        (2, 'Cancelado'),
    )
    
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Usuário',
        related_name='enrollments', on_delete=models.PROTECT
    )
    course = models.ForeignKey(
        Course, verbose_name='Curso', related_name='enrollments',
        on_delete=models.PROTECT,
    )
    status = models.IntegerField(
        'Situação', choices=STATUS_CHOICES, default=1, blank=True
    )

    created_at = models.DateTimeField('Criado em ', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em ', auto_now=True)

    def active(self):
        self.status = 1
        self.save()

    def is_approved(self):
        return self.status == 1

    class Meta:
        verbose_name = 'Incrição'
        verbose_name_plural = 'Inscrições'
        unique_together = (('user', 'course'),)

simplemoc/simplemoc/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from polls.mail import send_mail_template
from polls.utils import generate_hash_key

from .models import PasswordReset

User = get_user_model()

class PasswordResetForm(forms.Form):

    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return email
        raise forms.ValidationError(
            'Nenhum usuário encontrado com este e-mail'
        )

    def save(self):
        user = User.objects.get(email=self.cleaned_data['email'])
        key = generate_hash_key(user.username)
        reset = PasswordReset(key=key, user=user)
        reset.save()
        template_name = 'accounts/password_reset_email.html'
        subject = 'Criar nova senha no Simple MOOC'
        context = {
            'reset': reset,
        }
        send_mail_template(subject, template_name, context, [user.email])

class RegisterForm(forms.ModelForm):

    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmação de senha', widget=forms.PasswordInput)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('As senhas não coincidem')
        
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user
    
    class Meta:
        model = User
        fields = ['username', 'email']


class EditAccountForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ['username', 'email', 'name']

simplemoc/simplemoc/courses/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings

from polls.mail import send_mail_template

class ContactCourse(forms.Form):
    
    name = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(
        label='Mensagem/Dúvida', widget=forms.Textarea
    )

    def send_mail(self, course):
        subject = '[%s] Contato' % course
        context= {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message']
        }
        template_name = 'courses/contact_email.html'
        send_mail_template(
            subject, template_name, context, [settings.CONTACT_EMAIL]
        )

simplemoc/simplemoc/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.conf import settings
from django.contrib import messages

from django.contrib.auth import authenticate, login, update_session_auth_hash, get_user_model
from django.contrib.auth.forms import (
    UserCreationForm, PasswordChangeForm, SetPasswordForm)
from django.contrib.auth.decorators import login_required

from polls.utils import generate_hash_key
from simplemoc.courses.models import Enrollment

from .forms import RegisterForm, EditAccountForm, PasswordResetForm
from .models import PasswordReset

User = get_user_model()


@login_required()
def dashboard(request):
    template_name = 'accounts/dashboard.html'
    context = {}
    return render(request, template_name, context)

def register(request):
    template_name = 'accounts/register.html'

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username,
                password=form.cleaned_data['password1']
            )
            login(request, user)
            return redirect('polls:home')
    else:
        form = RegisterForm()

    context = {
        'form': form
    }

    return render(request, template_name, context)


def password_reset(request):
    template_name = 'accounts/password_reset.html'
    context = {}
    form = PasswordResetForm(request.POST or None)

    if form.is_valid():
        form.save()
        context['success'] = True

    context['form'] = form
    return render(request, template_name, context)


def password_reset_confirm(request, key):
    template_name = 'accounts/password_reset_confirm.html'
    context = {}
    reset = get_object_or_404(PasswordReset, key=key)
    form = SetPasswordForm(user=reset.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)


@login_required()
def edit(request):
    template_name = 'accounts/edit.html'
    context = {}
    if request.method == 'POST':
        form = EditAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Os dados da sua conta foram atualizados.'
            )
            return redirect('accounts:dashboard')
    else:
        form = EditAccountForm(instance=request.user)

    context['form'] = form
    return render(request, template_name, context)


@login_required()
def edit_password(request):
    template_name = 'accounts/edit_password.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            context['success'] = True
    else:
        form = PasswordChangeForm(user=request.user)

    context['form'] = form
    return render(request, template_name, context)

simplemoc/simplemoc/courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Course, Enrollment
from .forms import ContactCourse

def index(request):
    courses = Course.objects.all()
    template_name = 'courses/index.html'
    context = {
        'courses': courses,
    }
    return render(request, template_name, context)

def details(request, slug):
    course = get_object_or_404(Course, slug=slug)
    context = {}

    if request.method == 'POST':
        form = ContactCourse(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            form.send_mail(course)
            form = ContactCourse()
    else:
        form = ContactCourse()
    
    context['course'] = course
    context['form'] = form
    template_name = 'courses/details.html'

    return render(request, template_name, context)

@login_required()
def enrollment(request, slug):
    course = get_object_or_404(Course, slug=slug)
    enrollment, created = Enrollment.objects.get_or_create(
        user=request.user, course=course
    )
    if created:
        #enrollment.active()
        messages.success(request, 'Você foi inscrito no curso com sucesso.')
    else:
        messages.info(request, 'Você já está inscrito no curso.')

    return redirect('accounts:dashboard')

@login_required()
def announcements(request, slug):
    course = get_object_or_404(Course, slug=slug)
    if not request.user.is_staff:
        enrollment = get_object_or_404(
            Enrollment, user=request.user, course=course
        )
        if not enrollment.is_approved():
            messages.error(request, 'A sua inscrição está pendente')
            return redirect('accounts:dashboard')
    
    template_name = 'courses/announcements.html'
    context = {
        'course': course
    }
    return render(request, template_name, context)

@login_required()
def undo_enrollment(request, slug):
    course = get_object_or_404(Course, slug=slug)
    enrollment = get_object_or_404(
        Enrollment, user=request.user, course=course
    )
    if request.method == 'POST':
        enrollment.delete()
        messages.success(request, 'Sua inscrição foi cancelada')
        return redirect('accounts:dashboard')

    template = 'courses/undo_enrollment.html'
    context = {
        'enrollment': enrollment,
        'course': course,
    }
    return render(request, template, context)

simplemoc/simplemoc/courses/templates/courses/account.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância" />
    <title>Simple MOOC</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="css/styles.css" />
</head>

<body>
    <div class="header">
        <div class="pure-menu pure-menu-open pure-menu-fixed pure-menu-horizontal">
            <a class="pure-menu-heading" href="">SIMPLE MOOC</a>
            <ul>
                <li class="pure-menu-selected"><a href="#>Início</a></li>
            <li><a href=" #">Cursos</a></li>
                <li><a href="#">Contato</a></li>
                <li><a href="" title="">Entrar</a></li>
            </ul>
        </div>
    </div>
    <div class="content">
        <div class="pure-g-r content-ribbon">
            <aside class="pure-u-1">
                <p>Mensagem informativa de sucesso</p>
            </aside>
            <div class="pure-u-1">
                <ul class="breadcrumb">
                    <li><a herf"#">Meu Painel</a></li>
                    <li>/</li>
                    <li><a herf"#">Editar Conta</a></li>
                </ul>
            </div>
            <div class="pure-u-1-3">
                <h2>Meu painel</h2>
                <div class="pure-menu pure-menu-open">
                    <a class="pure-menu-heading">Meus Cursos</a>
                    <ul>
                        <li><a href="#">Curso 1</a></li>
                        <li><a href="#">Curso 2</a></li>
                        <li class="pure-menu-heading">Minha Conta</li>
                        <li><a href="#">Editar Conta</a></li>
                        <li><a href="#">Editar Senha</a></li>
                    </ul>
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class"inner">
                    <h2>Meus Cursos</h2>
                    <div class="well">
                        <h3>Python</h3>
                        <p>Python é uma linguagem de programação de alto nível, 
                        interpretada, de script, imperativa, orientada a objetos, 
                        funcional, de tipagem dinâmica e forte.</p>
                        <div class="pure-controls">
                            <a href="#" class="pure-button pure-button-primary">Acessar</a>
                            <a href="#" class="pure-button pure-button-error">Cancelar</a>
                        </div>
                    </div>
                    <aside class="pure-u-1">
                        <p>Nenhum curso inscrito</p>
                    </aside>
                </div>
            </div>
        </div>
        <div class="footer">
            Simple MOOC - Uma simples plataforma de ensino a distância
        </div>
    </div>
    <script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
</body>

</html>

simplemoc/simplemoc/courses/templates/courses/announcements.html
{% extends "courses/course_dashboard.html" %}

{% block dashboard_content %}
<h2>{{ course }}</h2>

<p>{{ course.about|linebreaks }}</p>
{% endblock %}

simplemoc/simplemoc/courses/templates/courses/contact_email.html
<p><strong>Nome</strong>: {{ name }} </p>
<p><strong>E-mail</strong>: {{ email }}</p>
{{ message|linebreaks }}

simplemoc/simplemoc/courses/templates/courses/course_dashboard.html
{% extends "accounts/dashboard.html" %}

{% block menu_options %}
<li class="pure-menu-heading">
    {{ course }}
</li>
<li>
    <a href="#">
        <i class="fa fa-video"></i>
        Aulas e Materiais
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-info-circle"></i>
        Informações
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-envelope"></i>
        Anúncios
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-comments"></i>
        Fórum de Dúvidas
    </a>
</li>
{{ block.super }}
{% endblock %}

simplemoc/simplemoc/courses/templates/courses/details.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="splash">
        <div class="pure-g-r">
                <div class="pure-u-1">
                        <div class="l-box splash-text">
                            <h1 class="splash-head">
                                {{ course }}
                            </h1>
                            <h2 class="splash-subhead">
                                {{ course.description }}
                            </h2>
                            <p>
                                <a href="{% url 'courses:enrollment' course.slug %}" class="pure-button primary-button">Increva-se</a>
                            </p>
                        </div>
                </div>
        </div>
</div>
<div class="pure-g-r content-ribbon">
        <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Sobre o curso</h4>
                    {{ course.about|linebreaks }}
                </div>
        </div>
        <div class="pure-u-1-3">
                <div class="l-box">
                    {% if course.image %}
                    <img src="{{ course.image.url }}" alt="">
                    {% else %}
                    <img src="{% static 'img/course.jpg' %}" alt="">
                    {% endif %}
                    <h4>Dúvidas?</h4>
                    <p>
                        <a href="#contato" title="" class="pure-button">Fale Conosco</a>
                    </p>
                </div>
        </div>
</div>
<div class="pure-g-r content-ribbon" id="contato">
    <div class="pure-u-1">
        <h3>Tire sua dúvida sobre o Curso</h3>
        {% if is_valid %}
        <p>Você enviou o formulário com sucesso.</p>
        {% endif %}
        <form action="#contato" class="pure-form pure-form-aligned" method="POST">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-control-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>

{% endblock %}

simplemoc/simplemoc/courses/templates/courses/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <h4 class="content-subhead">Listagem de Cursos do SimpleMOOC</h4>
            <p>Abaixo a lista de cursos disponíveis na plataforma</p>
        </div>
    </div>
</div>
{% for course in courses %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <a href="{{ course.get_absolute_url }}">
                {%if course.image %}
                <img src="{{ course.image.url }}" alt="{{ course }}">
                {% else %}
                <img src="{% static 'img/course.jpg' %}" alt="{{ course }}">
                {% endif %}
            </a>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead"><a href="{{ course.get_absolute_url }}">{{ course.name }}</a></h4>
            {{ course.description|linebreaks }}
        </div>
    </div>
</div>
{% empty %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <p>Nenhum curso disponível na plataforma</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

simplemoc/simplemoc/courses/templates/courses/undo_enrollment.html
{% extends "courses/course_dashboard.html" %}

{% block dashboard_content %}
<form action="" method="POST">
    {% csrf_token %}
    <h3>Você deseja realmente cancelar a inscrição deste curso?</h3>
    <div class="pure-controls">
        <button type="submit" class="pure-button button-error">Confirmar</button>
        <a href="{% url 'courses:announcements' course.slug %}" class="pure-button">Cancelar</a>
    </div>
</form>
{% endblock %}